# Generated by Django 3.1.2 on 2020-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('shortened_url_path', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Short URL path')),
            ],
        ),
    ]
