# Generated by Django 3.1.2 on 2020-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Active'),
        ),
        migrations.AlterIndexTogether(
            name='shortenedurl',
            index_together={('shortened_url_path', 'active')},
        ),
    ]
