# Generated by Django 3.1.2 on 2020-10-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20201014_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_clicked', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('referer', models.URLField(null=True, verbose_name='HTTP Referer')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl', verbose_name='URL')),
            ],
        ),
    ]
