# Generated by Django 3.1.2 on 2020-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_urlclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlclick',
            options={'ordering': ('-time_clicked',)},
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration time'),
        ),
        migrations.AlterIndexTogether(
            name='shortenedurl',
            index_together={('shortened_url_path', 'active', 'expiration_time')},
        ),
    ]
